#!/usr/bin/env bash

set -eo pipefail

if [[ "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_SKIP_CHECKOUT" == "true" \
    || "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_DELETE_CHECKOUT" != "true" ]]; then
  exit 0
fi

if [[ "${BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_USE_SUDO}" == "true" ]]; then
  SUDO_BIN="sudo"
else
  SUDO_BIN=""
fi

echo "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"

# Only try sudo if deleting without sudo fails
[ -z "${BUILDKITE_BUILD_CHECKOUT_PATH:-}" ] || {
  $SUDO_BIN rm -rf "${BUILDKITE_BUILD_CHECKOUT_PATH:?path_is_not_set}/*" 2>/dev/null
}

echo "Cleanup completed successfully."
